[workspace]
resolver = "3"
members = [
  # packages using a unified version
  "lucu",
  "lucu-llvm",
  "lucu-cli",
  "lucu-fmt",
  "lucu-lsp",
  "mu",
  "mu-llvm",
  # libraries using their own versioning scheme
  "asta-annotate",
  "asta-pretty",
  "asta-handle-map",
]

[workspace.package]
version = "0.2.0"

[workspace.dependencies]
inkwell = { version = "0.9.0", features = ["llvm21-1"] }
compact_str = "0.9.0"
anstyle = { version = "1.0.13", default-features = false }
include_dir = "0.7.4"
