[[language]]
name = "lucu"
scope = "source.lucu"
injection-regex = "lucu"
file-types = ["lucu"]
comment-tokens = ["--", "--#"]
indent = { tab-width = 4, unit = "    " }
formatter = { command = "cargo", args = ["run", "--bin", "lucu-fmt"] }
# language-servers = ["lucu-lsp"]
roots = ["main.lucu"]

# [language-server.lucu-lsp]
# command = "cargo"
# args = ["run", "--bin", "lucu-lsp"]
