[package]
name = "lucu-cli"
version.workspace = true
edition = "2024"

[dependencies]
compact_str = { workspace = true }
lucu = { path = "../lucu", features = ["watcher", "print"] }
lucu-llvm = { path = "../lucu-llvm" }
mu = { path = "../mu" }
mu-llvm = { path = "../mu-llvm" }
inkwell = { workspace = true }
asta-annotate = { path = "../asta-annotate" }
asta-handle-map = { path = "../asta-handle-map" }

anstream = "0.6.21"
facet = "0.43.2"
facet-args = "0.43.2"
