[package]
name = "lucu"
version = "0.1.0"
edition = "2024"

[dependencies]
lucu-annotate = { path = "../lucu-annotate" }

anstyle.workspace = true
include_dir.workspace = true

anstream = "0.6.21"
compact_str = "0.9.0"
crossbeam-channel = "0.5.15"
do-notation = "0.1.3"
im = "15.1.0"
lasso = "0.7.3"
notify-debouncer-full = { version = "0.6.0", features = ["crossbeam-channel"] }
path-clean = "1.0.1"
petgraph = { version = "0.8.3", path="../../petgraph", default-features = false, features = ["std"] }
strum = { version = "0.27.2", features = ["derive"] }
itertools = "0.14.0"
line-column = "0.2.0"
indexmap = "2.13.0"
