name: CI
on:
  pull_request:
  push:
    branches:
      - main
      - lambda

jobs:
  clippy:
    name: Lint with Clippy
    runs-on: ubuntu-24.04
    env:
      RUSTFLAGS: -Dwarnings
    steps:
      - uses: actions/checkout@v2
      - uses: hecrj/setup-rust-action@v1
        with:
          components: clippy
      - run: sudo apt install llvm-18-dev
      - run: cargo clippy --workspace --all-targets --verbose --no-default-features
      - run: cargo clippy --workspace --all-targets --verbose --all-features
  rustfmt:
    name: Verify code formatting
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v2
      - uses: hecrj/setup-rust-action@v1
        with:
          components: rustfmt
      - run: cargo fmt --all -- --check
  test-versions:
    name: Test Rust ${{ matrix.rust }}
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        rust: [stable, beta, nightly]
    steps:
      - uses: actions/checkout@v2
      - uses: hecrj/setup-rust-action@v1
        with:
          rust-version: ${{ matrix.rust }}
      - run: sudo apt install llvm-18-dev libpolly-18-dev
      - run: cargo test --verbose --workspace --all-features
      - run: cargo test --verbose --workspace --no-default-features
